"""Training helpers for CodeLeWM."""

from __future__ import annotations

from .config import (
    DEFAULT_SMALL_TRAIN_CONFIG,
    DEFAULT_TINY_TRAIN_CONFIG,
    SCALED_TRAIN_CONFIGS,
    TRAIN_CONFIG_SCHEMA_VERSION,
    LoaderConfig,
    OptimizerConfig,
    OutputConfig,
    TrainConfig,
    TrainConfigError,
    TrainDataConfig,
    TrainerConfig,
    TrainingLossConfig,
    WorldModelTrainConfig,
    default_train_config_paths,
    load_default_train_configs,
    load_scaled_train_configs,
    load_train_config,
    scaled_train_config_paths,
    validate_train_config,
)
from .cpu_smoke import (
    CPU_SMOKE_CHECKPOINT_SCHEMA_VERSION,
    CPU_SMOKE_REPORT_SCHEMA_VERSION,
    cpu_smoke_training_executor,
    train_cpu_smoke,
)
from .resume import (
    CheckpointResumePlan,
    compatibility_config_payload,
    prepare_checkpoint_resume,
)
from .runner import (
    TRAINING_METRICS_SCHEMA_VERSION,
    TRAINING_RUN_MANIFEST_SCHEMA_VERSION,
    TrainingExecutor,
    TrainingExecutorResult,
    TrainingRunContext,
    TrainingRunError,
    TrainingRunManifest,
    read_training_run_manifest,
    train,
)
from .torch_executor import (
    DEFAULT_TRAINING_VOCAB_SIZE,
    TORCH_CHECKPOINT_SCHEMA_VERSION,
    TORCH_TRAINING_REPORT_SCHEMA_VERSION,
    PackedTransitionHdf5Dataset,
    make_torch_training_executor,
    torch_training_executor,
    train_torch,
)

__all__ = [
    "CPU_SMOKE_CHECKPOINT_SCHEMA_VERSION",
    "CPU_SMOKE_REPORT_SCHEMA_VERSION",
    "CheckpointResumePlan",
    "DEFAULT_SMALL_TRAIN_CONFIG",
    "DEFAULT_TINY_TRAIN_CONFIG",
    "DEFAULT_TRAINING_VOCAB_SIZE",
    "LoaderConfig",
    "OptimizerConfig",
    "OutputConfig",
    "TRAINING_METRICS_SCHEMA_VERSION",
    "TRAINING_RUN_MANIFEST_SCHEMA_VERSION",
    "TRAIN_CONFIG_SCHEMA_VERSION",
    "TORCH_CHECKPOINT_SCHEMA_VERSION",
    "TORCH_TRAINING_REPORT_SCHEMA_VERSION",
    "PackedTransitionHdf5Dataset",
    "SCALED_TRAIN_CONFIGS",
    "TrainConfig",
    "TrainConfigError",
    "TrainDataConfig",
    "TrainerConfig",
    "TrainingExecutor",
    "TrainingExecutorResult",
    "TrainingLossConfig",
    "TrainingRunContext",
    "TrainingRunError",
    "TrainingRunManifest",
    "WorldModelTrainConfig",
    "compatibility_config_payload",
    "cpu_smoke_training_executor",
    "default_train_config_paths",
    "load_default_train_configs",
    "load_scaled_train_configs",
    "load_train_config",
    "make_torch_training_executor",
    "prepare_checkpoint_resume",
    "read_training_run_manifest",
    "scaled_train_config_paths",
    "train",
    "train_cpu_smoke",
    "train_torch",
    "torch_training_executor",
    "validate_train_config",
]
