"""Harness entry points for CodeLeWM."""

from __future__ import annotations

from collections.abc import Sequence

from .transition_index import (
    TRANSITION_INDEX_SCHEMA_VERSION,
    TransitionIndex,
    TransitionIndexEntry,
    TransitionIndexError,
    TransitionIndexSearchHit,
    build_transition_index,
    read_transition_index,
    transition_index_header_json_schema,
    write_transition_index,
)
from .index_runner import (
    INDEX_BUILD_RESULT_SCHEMA_VERSION,
    IndexBuildResult,
    build_transition_index_artifact,
)
from .quality import (
    SCORER_QUALITY_CONFIG_SCHEMA_VERSION,
    SCORER_QUALITY_REPORT_SCHEMA_VERSION,
    SCORER_QUALITY_RUN_SCHEMA_VERSION,
    ScorerQualityConfig,
    ScorerQualityError,
    ScorerQualityExampleConfig,
    ScorerQualityRunResult,
    read_scorer_quality_config,
    read_scorer_quality_report,
    run_scorer_quality_evaluation,
)
from .openrouter_adapter import (
    DEFAULT_OPENROUTER_MANAGEMENT_KEY_ENV,
    DEFAULT_OPENROUTER_MODEL,
    LLM_CANDIDATE_PACK_ARTIFACT_SCHEMA_VERSION,
    LLM_CANDIDATE_PACK_SCHEMA_VERSION,
    MAX_CAPTURE_PATCH_CHARS,
    OPENROUTER_ADAPTER_VERSION,
    OPENROUTER_BYOK_REGISTER_SCHEMA_VERSION,
    OPENROUTER_CANDIDATE_REQUEST_SCHEMA_VERSION,
    OPENROUTER_SDK_VERSION_PIN,
    CandidatePackArtifactResult,
    LLMCandidate,
    LLMCandidatePack,
    OpenRouterBYOKConfig,
    OpenRouterBYOKRegisterResult,
    OpenRouterAdapterError,
    OpenRouterCandidateRequest,
    capture_candidate_pack,
    generate_candidate_pack,
    llm_candidate_pack_json_schema,
    register_openrouter_byok_credential,
    render_candidate_prompt,
    write_candidate_pack_artifact,
)
from .llm_demo import (
    LLM_WORLD_MODEL_DEMO_REPORT_SCHEMA_VERSION,
    LLM_WORLD_MODEL_DEMO_RUN_SCHEMA_VERSION,
    LLMWorldModelDemoError,
    LLMWorldModelDemoRunResult,
    read_llm_world_model_demo_report,
    render_llm_world_model_demo_html,
    run_llm_world_model_demo,
)
from .visual_view_model import (
    DEMO_VISUAL_VIEW_MODEL_SCHEMA_VERSION,
    DemoVisualViewModelError,
    build_demo_visual_view_model,
    read_demo_visual_view_model,
    validate_demo_visual_view_model_payload,
    write_demo_visual_view_model,
)
from .demo_scenarios import (
    DEFAULT_DEMO_SCENARIO_ID,
    DEMO_SCENARIO_SCHEMA_VERSION,
    EXECUTION_RERANK_SCENARIO_ID,
    DemoScenario,
    DemoScenarioError,
    DemoScenarioFile,
    get_demo_scenario,
    list_demo_scenarios,
    materialize_demo_scenario,
    write_demo_scenario_shell_env,
)
from .execution_rerank_view_model import (
    EXECUTION_RERANK_VIEW_MODEL_SCHEMA_VERSION,
    CompletionPanelEntry,
    ExecutionRerankViewModel,
    ExecutionRerankViewModelError,
    build_execution_rerank_view_model,
)
from .scorer import (
    ERROR_REPORT_SCHEMA_VERSION,
    RERANK_RESULT_SCHEMA_VERSION,
    SCORE_RESULT_SCHEMA_VERSION,
    CodeLeWMScorer,
    ErrorReport,
    HashingTransitionScoringBackend,
    RerankResult,
    ScoreError,
    ScoreResult,
    TorchCheckpointTransitionScoringBackend,
    TransitionScoringBackend,
    error_report_json_schema,
    error_report_to_json,
    load_scorer,
    rerank_result_json_schema,
    rerank_result_to_json,
    score_input_digest,
    score_result_json_schema,
    score_result_to_json,
    validate_error_report_payload,
    validate_rerank_result_payload,
    validate_score_result_payload,
)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the CLI entry point without importing it during package initialization."""

    from .cli import main as _main

    return _main(argv)


__all__ = [
    "ERROR_REPORT_SCHEMA_VERSION",
    "CompletionPanelEntry",
    "EXECUTION_RERANK_SCENARIO_ID",
    "EXECUTION_RERANK_VIEW_MODEL_SCHEMA_VERSION",
    "ExecutionRerankViewModel",
    "ExecutionRerankViewModelError",
    "build_execution_rerank_view_model",
    "INDEX_BUILD_RESULT_SCHEMA_VERSION",
    "LLM_CANDIDATE_PACK_ARTIFACT_SCHEMA_VERSION",
    "LLM_CANDIDATE_PACK_SCHEMA_VERSION",
    "LLM_WORLD_MODEL_DEMO_REPORT_SCHEMA_VERSION",
    "LLM_WORLD_MODEL_DEMO_RUN_SCHEMA_VERSION",
    "MAX_CAPTURE_PATCH_CHARS",
    "OPENROUTER_ADAPTER_VERSION",
    "OPENROUTER_BYOK_REGISTER_SCHEMA_VERSION",
    "OPENROUTER_CANDIDATE_REQUEST_SCHEMA_VERSION",
    "OPENROUTER_SDK_VERSION_PIN",
    "RERANK_RESULT_SCHEMA_VERSION",
    "SCORER_QUALITY_CONFIG_SCHEMA_VERSION",
    "SCORER_QUALITY_REPORT_SCHEMA_VERSION",
    "SCORER_QUALITY_RUN_SCHEMA_VERSION",
    "SCORE_RESULT_SCHEMA_VERSION",
    "TRANSITION_INDEX_SCHEMA_VERSION",
    "CodeLeWMScorer",
    "CandidatePackArtifactResult",
    "DEFAULT_OPENROUTER_MANAGEMENT_KEY_ENV",
    "DEFAULT_DEMO_SCENARIO_ID",
    "DEFAULT_OPENROUTER_MODEL",
    "DEMO_SCENARIO_SCHEMA_VERSION",
    "DEMO_VISUAL_VIEW_MODEL_SCHEMA_VERSION",
    "DemoScenario",
    "DemoScenarioError",
    "DemoScenarioFile",
    "DemoVisualViewModelError",
    "ErrorReport",
    "HashingTransitionScoringBackend",
    "IndexBuildResult",
    "LLMCandidate",
    "LLMCandidatePack",
    "LLMWorldModelDemoError",
    "LLMWorldModelDemoRunResult",
    "OpenRouterBYOKConfig",
    "OpenRouterBYOKRegisterResult",
    "OpenRouterAdapterError",
    "OpenRouterCandidateRequest",
    "RerankResult",
    "ScoreError",
    "ScoreResult",
    "ScorerQualityConfig",
    "ScorerQualityError",
    "ScorerQualityExampleConfig",
    "ScorerQualityRunResult",
    "TorchCheckpointTransitionScoringBackend",
    "TransitionIndex",
    "TransitionIndexEntry",
    "TransitionIndexError",
    "TransitionIndexSearchHit",
    "TransitionScoringBackend",
    "build_transition_index",
    "build_transition_index_artifact",
    "build_demo_visual_view_model",
    "capture_candidate_pack",
    "error_report_json_schema",
    "error_report_to_json",
    "generate_candidate_pack",
    "get_demo_scenario",
    "llm_candidate_pack_json_schema",
    "list_demo_scenarios",
    "load_scorer",
    "main",
    "materialize_demo_scenario",
    "read_transition_index",
    "read_scorer_quality_config",
    "read_scorer_quality_report",
    "read_llm_world_model_demo_report",
    "read_demo_visual_view_model",
    "register_openrouter_byok_credential",
    "rerank_result_json_schema",
    "rerank_result_to_json",
    "render_candidate_prompt",
    "render_llm_world_model_demo_html",
    "score_input_digest",
    "score_result_json_schema",
    "score_result_to_json",
    "run_scorer_quality_evaluation",
    "run_llm_world_model_demo",
    "transition_index_header_json_schema",
    "validate_error_report_payload",
    "validate_demo_visual_view_model_payload",
    "validate_rerank_result_payload",
    "validate_score_result_payload",
    "write_candidate_pack_artifact",
    "write_demo_visual_view_model",
    "write_demo_scenario_shell_env",
    "write_transition_index",
]
