"""Model components for CodeLeWM."""

from __future__ import annotations

from .transition import (
    ABSTRACT_ACTION_SEQUENCE_LENGTH,
    LATENT_DIM,
    STATE_SEQUENCE_LENGTH,
    TEXT_ACTION_SEQUENCE_LENGTH,
    ActionBatch,
    CodeStateBatch,
    CodeTransitionModel,
    TensorContract,
    TransitionBatch,
    expected_action_sequence_length,
    infer_shape,
    transition_energy,
)
from .actions import (
    ABSTRACT_ACTION_BASE_VOCABULARY,
    AbstractActionEncoder,
    AbstractActionEncoderConfig,
    AbstractActionTokenizer,
    ModelRuntimeUnavailableError,
    TextActionEncoder,
    TextActionEncoderConfig,
    TextActionTokenizer,
)
from .checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    DEFAULT_RECORD_SCHEMA_VERSION,
    CheckpointCompatibilityError,
    CheckpointCompatibilitySpec,
    CheckpointManifest,
    CheckpointMetadata,
    build_checkpoint_metadata,
    compute_config_hash,
    load_checkpoint_manifest,
    migrate_checkpoint_manifest,
    read_checkpoint_manifest,
    validate_checkpoint_compatibility,
    validate_checkpoint_file,
    write_checkpoint_manifest,
)
from .objective import (
    ObjectiveConfig,
    ObjectiveTerms,
    compute_action_swap_contrastive_loss,
    compute_action_use_margin_loss,
    compute_in_batch_retrieval_loss,
    compute_inverse_action_reconstruction_loss,
    compute_prediction_mse,
    compute_retrieval_score_matrix,
    compute_sigreg_loss,
    compute_transition_objective,
    stack_objective_embeddings,
)
from .predictor import (
    CodeLatentPredictor,
    CodeLatentPredictorConfig,
)
from .state import (
    CodeStateEncoder,
    CodeStateEncoderConfig,
)
from .torch_transition import (
    TorchCodeTransitionModel,
    TorchCodeTransitionModelConfig,
    build_torch_transition_model,
    resolve_state_encoder_arch,
)

__all__ = [
    "ABSTRACT_ACTION_SEQUENCE_LENGTH",
    "ABSTRACT_ACTION_BASE_VOCABULARY",
    "CHECKPOINT_SCHEMA_VERSION",
    "DEFAULT_RECORD_SCHEMA_VERSION",
    "AbstractActionEncoder",
    "AbstractActionEncoderConfig",
    "AbstractActionTokenizer",
    "CheckpointCompatibilityError",
    "CheckpointCompatibilitySpec",
    "CheckpointManifest",
    "CheckpointMetadata",
    "CodeStateEncoder",
    "CodeStateEncoderConfig",
    "CodeLatentPredictor",
    "CodeLatentPredictorConfig",
    "LATENT_DIM",
    "ObjectiveConfig",
    "ObjectiveTerms",
    "STATE_SEQUENCE_LENGTH",
    "TEXT_ACTION_SEQUENCE_LENGTH",
    "ActionBatch",
    "CodeStateBatch",
    "CodeTransitionModel",
    "ModelRuntimeUnavailableError",
    "TensorContract",
    "TextActionEncoder",
    "TextActionEncoderConfig",
    "TorchCodeTransitionModel",
    "TorchCodeTransitionModelConfig",
    "TextActionTokenizer",
    "TransitionBatch",
    "build_checkpoint_metadata",
    "build_torch_transition_model",
    "resolve_state_encoder_arch",
    "compute_action_swap_contrastive_loss",
    "compute_action_use_margin_loss",
    "compute_config_hash",
    "compute_in_batch_retrieval_loss",
    "compute_inverse_action_reconstruction_loss",
    "compute_prediction_mse",
    "compute_retrieval_score_matrix",
    "compute_sigreg_loss",
    "compute_transition_objective",
    "expected_action_sequence_length",
    "infer_shape",
    "load_checkpoint_manifest",
    "migrate_checkpoint_manifest",
    "read_checkpoint_manifest",
    "stack_objective_embeddings",
    "transition_energy",
    "validate_checkpoint_compatibility",
    "validate_checkpoint_file",
    "write_checkpoint_manifest",
]
